# Tuplas com time de Futebol
lista = ('Corinthians', 'Atlético-MG', 'São Paulo', 'Botafogo', 'Santos', 'Coritiba', 'Avaí', 'América-MG', 'Palmeiras', 'Bragantino', 'Internacional', 'Fluminense', 'Goiás', 'Cuiabá', 'Athletico-PR', 'Flamengo', 'Juventude', 'Ceará', 'Atlético-GO', 'Fortaleza')
print (f'lista dos times do Brasileirão {lista}')
type(lista)
tupla_primeiros = ('Corinthians', 'Atlético-MG', 'São Paulo', 'Botafogo', 'Santos')
print('-='*15)
print(f'Os 5 primeiros time são: {tupla_primeiros}')
print('-='*15)
tuplas_finais = ('Juventude', 'Ceará', 'Atlético-GO', 'Fortaleza' )
print('-='*15)
print(f'Os 4 ultimos são:{tuplas_finais} ')
print('-='*15)
print(f'Times em ordem alfabética: {sorted(lista)}')
print('-='*15)